/**
 * ElectroInfo — Firebase Cloud Functions
 *
 * - sendEmail     : envoi newsletter via Brevo (existant)
 * - generateFiche : proxy Anthropic pour l'encyclopédie (nouveau)
 *
 * CONFIGURATION :
 *   firebase functions:config:set anthropic.key="sk-ant-VOTRE_CLE"
 */

const { onDocumentCreated } = require("firebase-functions/v2/firestore");
const functions             = require("firebase-functions");
const admin                 = require("firebase-admin");
const nodemailer            = require("nodemailer");
const fetch                 = require("node-fetch");

admin.initializeApp();

// ══════════════════════════════════════════════════════
// 1. SEND EMAIL — Newsletter Brevo (fonction existante)
// ══════════════════════════════════════════════════════
const transporter = nodemailer.createTransport({
  host:   "smtp-relay.brevo.com",
  port:   587,
  secure: false,
  auth: {
    user: "",
    pass: process.env.SMTP_PASSWORD,
  },
});

exports.sendEmail = onDocumentCreated("newsletter_sends/{sendId}", async (event) => {
  const snapshot = event.data;
  if (!snapshot) return null;

  const data = snapshot.data();
  const mailOptions = {
    from:    '"ElectroInfo" <doanyonafrica@gmail.com>',
    to:      data.email,
    subject: data.subject     || "Test Newsletter",
    html:    data.htmlContent || "<p>Connexion réussie !</p>",
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log("✅ Email envoyé à :", data.email);
    return snapshot.ref.update({ status: "sent", sentAt: new Date().toISOString() });
  } catch (error) {
    console.error("❌ Erreur :", error);
    return snapshot.ref.update({ status: "error", error: error.message });
  }
});

// ══════════════════════════════════════════════════════
// 2. GENERATE FICHE — Proxy Anthropic encyclopédie
// ══════════════════════════════════════════════════════
const ALLOWED_ORIGINS = [
  "https://electroinfo.online",
  "https://www.electroinfo.online",
  "http://localhost:5173",
  "http://localhost:3000",
  "http://127.0.0.1:5500",
];

function setCors(req, res) {
  const origin = req.headers.origin;
  res.set("Access-Control-Allow-Origin",  ALLOWED_ORIGINS.includes(origin) ? origin : "*");
  res.set("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.set("Access-Control-Allow-Headers", "Content-Type");
  res.set("Access-Control-Max-Age",       "3600");
}

exports.generateFiche = functions
  .region("europe-west1")
  .runWith({ timeoutSeconds: 60, memory: "256MB" })
  .https.onRequest(async (req, res) => {

    setCors(req, res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }
    if (req.method !== "POST")   { res.status(405).json({ error: "POST uniquement" }); return; }

    const query = (req.body?.query || "").trim();
    if (!query || query.length < 2)  { res.status(400).json({ error: "Requête vide" }); return; }
    if (query.length > 200)          { res.status(400).json({ error: "Requête trop longue" }); return; }

    const apiKey = functions.config().anthropic?.key;
    if (!apiKey) {
      res.status(500).json({ error: "Clé API non configurée — firebase functions:config:set anthropic.key=\"sk-ant-...\"" });
      return;
    }

    const now    = new Date().toISOString();
    const prompt = `Tu es une encyclopédie francophone spécialisée en électricité industrielle, électronique et technologie électrique.

Génère une fiche encyclopédique COMPLÈTE en JSON pour le sujet : "${query}"

RÈGLES STRICTES :
- Répondre UNIQUEMENT avec du JSON valide, sans backticks, sans texte avant ou après
- Schéma exact :
{
  "id": "slug-kebab-case",
  "icon": "emoji",
  "title": "Titre exact",
  "subtitle": "Sous-titre court",
  "tag": "composant" ou "electricite",
  "niveau": "Débutant" ou "Intermédiaire" ou "Avancé",
  "lecture": "X min",
  "summary": "Résumé 2-3 phrases",
  "infobox": [{"k":"clé","v":"valeur","mono":false}],
  "sections": [{"h2":"...","id":"...","html":"<p class=\\"art-p\\">...</p>","subs":[{"h3":"...","id":"...","html":"..."}]}],
  "refs": ["Auteur, Titre, Éditeur, Année."],
  "related": ["id-fiche-liee"],
  "autoGenerated": true,
  "updatedAt": "${now}"
}
- Minimum 4 sections H2 avec H3, infobox 4-7 lignes
- Formules dans <div class="formula">...</div>
- Contenu sérieux niveau technicien/étudiant francophone`;

    let anthropicRes;
    try {
      anthropicRes = await fetch("https://api.anthropic.com/v1/messages", {
        method:  "POST",
        headers: {
          "Content-Type":      "application/json",
          "x-api-key":         apiKey,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model:      "claude-sonnet-4-20250514",
          max_tokens: 4000,
          messages:   [{ role: "user", content: prompt }],
        }),
      });
    } catch (e) {
      console.error("Réseau Anthropic:", e.message);
      res.status(503).json({ error: "Impossible de joindre Anthropic" });
      return;
    }

    if (!anthropicRes.ok) {
      const t = await anthropicRes.text().catch(() => "");
      console.error("Anthropic erreur:", anthropicRes.status, t);
      res.status(502).json({ error: `Anthropic erreur ${anthropicRes.status}` });
      return;
    }

    const apiData = await anthropicRes.json();
    const raw     = apiData.content?.find(b => b.type === "text")?.text || "";
    const clean   = raw.replace(/```json|```/g, "").trim();

    let fiche;
    try {
      fiche = JSON.parse(clean);
    } catch (e) {
      console.error("JSON invalide:", clean.substring(0, 300));
      res.status(500).json({ error: "Réponse IA invalide" });
      return;
    }

    if (!fiche.id || !fiche.title || !fiche.sections) {
      res.status(500).json({ error: "Fiche incomplète" });
      return;
    }

    res.status(200).json({ fiche });
  });
